
<footer id="main-footer"> 
    <p>© Copyright CIE. Todos los Derechos Reservados. Desarrollo web por Kellyn Delgado.</p>     
    <a href="http://www.facebook.com"><img src="recursos/images/facebook.png" alt="Imagen del logo del sitio web facebook"></a>
    <a href="https://plus.google.com"><img src="recursos/images/google-plus.png" alt="Imagen del logo del sitio web Google-Plus" ></a>
    <a href="https://twitter.com"><img src="recursos/images/gorjeo.png" alt="Imagen del logo del sitio web Twitter"></a>
    <a href="https://www.linkedin.com/"><img src="recursos/images/linkedin.png" alt="Imagen del logo del sitio web Linkedin"></a>
    <a href="https://www.pinterest.es/"><img src="recursos/images/pinterest.png" alt="Imagen del logo del sitio web Pinterest"></a>  
</footer>     
